### ISSUE TITLE
package:school_book/api/api.dart error variable type

### ISSUE THREAD

**Issue by gorlik1337** [MatisiekPL/school-book#7]
I think this help you
i talking about fragments/grades branch

![image](https://user-images.githubusercontent.com/33355238/45103909-32e23700-b131-11e8-816e-27298839618f.png)

**Comment by MatisiekPL** [comment]
Yeah. I've discovered type mismatch few hours ago, but it was strange, that the dart virtual machine was not detected the error. In next commits, it was fixed. Closing issue
